FROM ghcr.io/sjinks/codespaces/wordpress-all-in-one:latest@sha256:3bdcbef432184bc68181a74066f54c5d18b708cc3d1cb41b7b6dc30a6ee4f02c

RUN apk add --no-cache --force-overwrite php8-pecl-xdebug@edget
COPY rootfs /
