#!/bin/sh

set -eu

exec 2>&1

: "${CONTAINER_USER:=nginx}"

PID_FILE=/run/nginx/nginx.pid

/usr/bin/install -d -o "${CONTAINER_USER}" -g "${CONTAINER_USER}" "${PID_FILE%/*}" /var/log/nginx
/usr/bin/install -d -o "${CONTAINER_USER}" -g "${CONTAINER_USER}" -m 0750 /var/lib/nginx
exec /usr/sbin/nginx -c /etc/nginx/nginx.conf -g "pid ${PID_FILE}; daemon off;"
